name: Easeml/CI
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'master'
      - 'feature/cicd'
  create:
    tags:
      - 'v*'
env:
    CI: true
    TERM: xterm
jobs:
    display_changes:
        runs-on: ubuntu-latest
        steps:
            - name: Install Prerequisites
              run: |
                echo "Initializing the software environment"
                apt update
                apt install -y build-essential python3-dev libssl-dev libffi-dev
                apt install -y ca-certificates curl gnupg lsb-release

                ####
                echo "Installing docker"
                echo "Adding docker gpg key"
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
                echo "Setting the correct docker repository"
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                echo "Updating APT"
                sudo apt update
                echo "Installing Docker engine"
                sudo apt install -y docker-ce docker-ce-cli containerd.io
                echo "Testing Docker"
                sudo docker run hello-world
            - name: Check out code
              uses: actions/checkout@v1

